name: signalalign
channels:
  - bioconda
  - anaconda
  - defaults
  - adbailey4
  - intel
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.6
  - curl=7.62.0
  - pip=18.1=py36_0
  - py=1.7.0=py36_0
  - python=3.6.7
  - scipy=1.1.0
  - six=1.11.0=py36_1
  - tk=8.6.8
  - xz=5.2.4
  - zlib=1.2.11
  - bwa=0.7.17
  - htslib=1.9
  - samtools=1.9
  - numpy=1.15.4
  - numpy-base=1.15.4
  - pytest=4.0.0=py36_0
  - setuptools=40.6.2=py36_0
  - wheel=0.32.3=py36_0
  - pysam=0.15.0
  - py3helpers=0.0.9
  - biopython=1.72
  - pip:
    - cycler==0.10.0
    - cython==0.29
    - h5py==2.8.0
    - mappy==2.8
    - matplotlib==2.0.2
    - pandas==0.23.4
    - python-dateutil==2.7.5
    - pyyaml==4.2b4
    - scikit-learn==0.19.0

