//
// Created by Andrew Bailey on 4/25/18.
//

#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <inttypes.h>
#include "CuTest.h"
#include "fasta_handler.h"
#include "signalMachineUtils.h"


static void test_fastaHandler_getSubSequence(CuTest *testCase) {
    char *test_fasta_path = "../../signalAlign/tests/test_sequences/pUC19_SspI_Zymo.fa";
    int start = 0;
    int end = 10;
    bool strand = 1;
    char *seq_name = "ZYMO";
    char *answer = "AGAATTGGTT";
    char *zymo = "AGAATTGGTTAATTGGTTGTAACACTGGCAGAGCATTACGCTGACTTGACGGGACGGCGGCTTTGTTGAATAAATCGAACTTTTGCTGAGTTGAAGGATCAGATCACGCATCTTCCCGACAACGCAGACCGTTCCGTGGCAAAGCAAAAGTTCAAAATCACCAACTGGTCCACCTACAACAAAGCTCTCATCAACCGTGGCTCCCTCACTTTCTGGCTGGATGATGGGGCGATTCAGGCCTGGTATGAGTCAGCAACACCTTCTTCACGAGGCAGACCTCAGCGCTCAAAGATGCAGGGGTAAAAGCTAACCGCATCTTTACCGACAAGGCATCCGGCAGTTCAACAGATCGGGAAGGGCTGGATTTGCTGAGGATGAAGGTGGAGGAAGGTGATGTCATTCTGGTGAAGAAGCTCGACCGTCTTGGCCGCGACACCGCCGACATGATCCAACTGATAAAAGAGTTTGATGCTCAGGGTGTAGCGGTTCGGTTTATTGACGACGGGATCAGTACCGACGGTGATATGGGGCAAATGGTGGTCACCATCCTGTCGGCTGTGGCACAGGCTGAACGCCGGAGGATCCTAGAGCGCACGAATGAGGGCCGACAGGAAGCAAAGCTGAAAGGAATCAAATTTGGCCGCAGGCGTACCGTGGACAGGAACGTCGTGCTGACGCTTCATCAGAAGGGCACTGGTGCAACGGAAATTGCTCATCAGCTCAGTATTGCCCGCTCCACGGTTTATAAAATTCTTGAAGACGAAAGGGCCTCGTGATACGCCTATTTTTATAGGTTAATGTCATGATAATAATGGTTTCTTAGACGTCAGGTGGCACTTTTCGGGGAAATGTGCGCGGAACCCCTATTTGTTTATTTTTCTAAATACATTCAAATAT";
    char *fasta_seq = fastaHandler_getSubSequence(test_fasta_path, start, end, strand, seq_name);
    char *signal_seq = signalUtils_getSubSequence(zymo, start, end, strand);

    CuAssertStrEquals(testCase, signal_seq, fasta_seq);
    CuAssertStrEquals(testCase, fasta_seq, answer);
}


CuSuite *fastaHandlerTestSuite(void) {
    CuSuite *suite = CuSuiteNew();

    SUITE_ADD_TEST(suite, test_fastaHandler_getSubSequence);

    return suite;
}

